import csv
import torch
from pathlib import Path
from tqdm import tqdm
from dp.phonemizer import Phonemizer


def prepare_everything(metadata_path, wavs_dir):
    print("Loading DeepPhonemizer (ARPA)...")

    _original_torch_load = torch.load

    def _torch_load_weights_only_false(*args, **kwargs):
        kwargs.setdefault("weights_only", False)
        return _original_torch_load(*args, **kwargs)

    torch.load = _torch_load_weights_only_false

    try:
        # NOTICE: We load the non-IPA checkpoint
        phonemizer = Phonemizer.from_checkpoint("pretrained_models/en_us_cmudict_forward.pt")
    finally:
        torch.load = _original_torch_load

    print(f"Processing {metadata_path}...")

    wavs_path = Path(wavs_dir)
    all_symbols = set()

    # Add special tokens
    all_symbols.add("pad")
    all_symbols.add("eos")
    all_symbols.add("spn")

    with open(metadata_path, 'r', encoding='utf-8') as f:
        reader = csv.reader(f, delimiter='|')
        rows = list(reader)

    print("Generating .lab files (ARPA)...")

    for row in tqdm(rows):
        if len(row) < 3: continue
        file_id = row[0]
        text = row[2]

        # 1. Get Phonemes (ARPA)
        # DeepPhonemizer output: "HH AH0 L OW1" (Already space separated!)
        raw_phonemes = phonemizer(text, lang='en_us')

        # 2. Split
        tokens = raw_phonemes.split()

        # 3. Clean and Collect
        clean_tokens = []
        for t in tokens:
            if t.strip():
                clean_tokens.append(t)
                all_symbols.add(t)

        # 4. Write .lab file
        lab_content = " ".join(clean_tokens)
        lab_path = wavs_path / f"{file_id}.lab"
        with open(lab_path, "w", encoding="utf-8") as lab_file:
            lab_file.write(lab_content)

    # 5. Save Dictionary for MFA (Mapping ARPA to ARPA)
    dict_path = "data/arpa_dict.txt"
    print(f"Saving MFA dictionary to {dict_path}...")

    sorted_symbols = sorted(list(all_symbols))

    with open(dict_path, "w", encoding="utf-8") as f:
        for s in sorted_symbols:
            if s in ["pad", "eos"]: continue
            f.write(f"{s} {s}\n")

        # Ensure special tokens exist
        if "spn" not in all_symbols: f.write("spn spn\n")
        if "sil" not in all_symbols: f.write("sil sil\n")

    # 6. Save Python Symbols
    py_path = "src/symbols.py"
    print(f"Saving Python symbols to {py_path}...")

    py_content = f"""# Auto-generated by src/prepare_mfa_labels.py
# Single source of truth for ARPA symbols

symbols = {sorted_symbols}

symbol_to_id = {{s: i for i, s in enumerate(symbols)}}
id_to_symbol = {{i: s for i, s in enumerate(symbols)}}
"""
    with open(py_path, "w", encoding="utf-8") as f:
        f.write(py_content)

    print("Done! Ready for MFA (english_us_arpa).")


if __name__ == "__main__":
    prepare_everything("data/LJSpeech-1.1/metadata.csv", "data/LJSpeech-1.1/wavs")